import './globals.css'
import {Inter} from 'next/font/google'

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        {/* 2 column wrapper */}
        <div className="flex flex-grow w-full min-h-screen">
            {/* Left sidebar & main wrapper */}
            <div className="flex-1 min-w-0 bg-gray-50 xl:flex">
                <div
                    className="border-b border-gray-200 xl:border-b-0 xl:flex-shrink-0 xl:w-72 xl:border-r xl:border-gray-200">
                    <div className="h-full pl-4 pr-6 py-6 sm:pl-6 lg:pl-8">
                        {/* Start left column area */}
                        <div className="h-full relative" style={{minHeight: '12rem'}}>
                            <div className="absolute inset-0 border-2 border-gray-200 border-dashed rounded-lg"/>
                        </div>
                        {/* End left column area */}
                    </div>
                </div>

                <div className="bg-white lg:min-w-0 lg:flex-1">
                    <div className="h-full py-6 px-4 sm:px-6 max-w-7xl mx-auto">
                        {/* Start the main area */}
                        {children}
                        {/* End main area */}
                    </div>
                </div>
            </div>
        </div>
        </body>
        </html>
    )
}
